
import type { Handler, HandlerEvent, HandlerContext } from "@netlify/functions";
import { sendEmail } from "./_lib/mailService";
import { safeError, logError } from "./_lib/errorHandler";

const CORS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type, Authorization, X-User-Id",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Content-Type": "application/json",
};

const handler: Handler = async (
    event: HandlerEvent,
    _ctx: HandlerContext
) => {
    // ── CORS preflight ──────────────────────────────────────────────
    if (event.httpMethod === "OPTIONS") {
        return { statusCode: 204, headers: CORS, body: "" };
    }

    if (event.httpMethod !== "POST") {
        return { statusCode: 405, headers: CORS, body: JSON.stringify({ error: "Method not allowed" }) };
    }

    let isEs = true;

    try {
        const userId = event.headers["x-user-id"] || event.headers["X-User-Id"] || "";
        const body = JSON.parse(event.body || "{}");
        const { email, pdfBase64, fileName, domain, reportType, language = "es" } = body;
        isEs = language === "es";

        console.log(`[api-send-report] User: ${userId}. Logged payload for ${email}. Domain: ${domain}, Report: ${reportType}`);

        if (!email || !pdfBase64) {
            console.error("[api-send-report] Missing email or pdf data");
            return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: "Missing email or pdf data" }) };
        }

        const pdfSize = pdfBase64.length;
        console.log(`[api-send-report] Received PDF payload: ${(pdfSize / 1024 / 1024).toFixed(2)}MB (base64)`);

        const MAX_B64_SIZE = 4 * 1024 * 1024; // 4MB
        if (pdfSize > MAX_B64_SIZE) {
            console.warn(`[api-send-report] PDF too large (${(pdfSize / 1024 / 1024).toFixed(1)}MB base64) — skipping attachment, sending link-only email.`);
        }
        const subject = isEs 
            ? `📄 Reporte de Auditoría: ${domain || fileName}` 
            : `📄 Audit Report: ${domain || fileName}`;

        const html = `
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #020617; color: #e2e8f0; border-radius: 12px; border: 1px solid #1e293b;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h1 style="color: #ff477b; margin: 0;">${isEs ? '¡Tu Reporte está listo!' : 'Your Report is Ready!'} 🚀</h1>
                </div>
                <p>${isEs ? 'Hola,' : 'Hello,'}</p>
                <p>${isEs 
                    ? `Adjunto encontrarás el reporte detallado generado por <strong>INsitu AI</strong> para <strong>${domain || fileName}</strong>.`
                    : `Attached you will find the detailed report generated by <strong>INsitu AI</strong> for <strong>${domain || fileName}</strong>.`}</p>
                <p>${isEs ? 'Este análisis incluye:' : 'This analysis includes:'}</p>
                <ul>
                    <li>${isEs ? 'Diagnóstico estratégico con IA' : 'Strategic AI diagnosis'}</li>
                    <li>${isEs ? 'Benchmarks de la industria' : 'Industry benchmarks'}</li>
                    <li>${isEs ? 'Recomendaciones de optimización' : 'Optimization recommendations'}</li>
                </ul>
                <div style="background: #1e293b; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #334155;">
                    <p style="margin: 0; font-size: 14px;"><strong>${isEs ? 'Tipo de Reporte:' : 'Report Type:'}</strong> ${reportType || (isEs ? "Auditoría General" : "General Audit")}</p>
                    <p style="margin: 5px 0 0; font-size: 14px;"><strong>${isEs ? 'Fecha:' : 'Date:'}</strong> ${new Date().toLocaleDateString(isEs ? 'es-ES' : 'en-US')}</p>
                </div>
                <p>${isEs ? 'Si tienes alguna duda sobre los resultados, puedes responder a este correo.' : 'If you have any questions about the results, you can reply to this email.'}</p>
                <p>${isEs ? 'Saludos,' : 'Best regards,'}<br>${isEs ? 'El equipo de INsitu AI' : 'The INsitu AI team'}</p>
                <hr style="border: 0; border-top: 1px solid #1e293b; margin: 20px 0;">
                <div style="text-align: center;">
                    <p style="font-size: 12px; color: #94a3b8;">© 2026 INsitu AI • <a href="https://insitu.company" style="color: #ff477b; text-decoration: none;">insitu.company</a></p>
                </div>
            </div>
        `;

        // Only attach PDF if it fits within limit
        const attachments = pdfSize <= MAX_B64_SIZE ? [
            {
                filename: fileName.endsWith(".pdf") ? fileName : `${fileName}.pdf`,
                content: pdfBase64.split("base64,")[1] || pdfBase64,
                encoding: 'base64' as const
            }
        ] : undefined;

        console.log(`[api-send-report] Attempting to send email to ${email}...`);
        await sendEmail(email, subject, html, attachments);
        console.log(`[api-send-report] Email sent successfully to ${email}`);

        return { statusCode: 200, headers: CORS, body: JSON.stringify({ success: true, message: "Email sent successfully" }) };
    } catch (err: any) {
        console.error("[api-send-report] CRITICAL Error:", err.message);
        return { 
            statusCode: 500, 
            headers: CORS, 
            body: JSON.stringify({ 
                error: (isEs ? "Error al enviar el email: " : "Email send error: ") + err.message 
            }) 
        };
    }
};

export { handler };
